# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# set workdir
WORKDIR /app

# install dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir mcp[cli]>=1.6.0 evolutionapi>=0.1.1 python-dotenv>=1.1.0

# copy source code
COPY . /app

# default entrypoint
ENTRYPOINT ["python", "-u", "evoapi_mcp.py"]
